[package]
name = "project_k_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
log4rs = { version = "1.3.0", features = ["threshold_filter"] }
parser = { path = "../parser" }
engine = {path = "../engine"}
miette = { version = "7.6.0", features = ["fancy"] }
